# Custom Language File for Launcher Customizer

[ejs.app]
title = "dangcheong"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/dangcheong"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/dangcheong"
supportLink = "https://github.com/mchlauncher/dangcheong/issues"

[ejs.welcome]
welcomeHeader = "dangcheong"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."